package com.example.shopmobile.common

import com.example.shopmobile.BuildConfig

object TestConfig {
    /**
     * CONFIGURATION TOGGLE
     * Generated by Gradle at build time based on -PuseMockServer property.
     * true  = Run tests against the local MockWebServer.
     * false = Run tests against the real backend (DEFAULT).
     */
    val USE_MOCK_SERVER = BuildConfig.USE_MOCK_SERVER

    // Dynamic Expected Data for Assertions
    // Updated to match realistic data ("Fjallraven - Foldsack No. 1 Backpack...")
    val FIRST_PRODUCT_TITLE: String
        get() = "Fjallraven - Foldsack No. 1 Backpack, Fits 15 Laptops"

    val FIRST_PRODUCT_PRICE: String
        get() = "$109.95"

    // Standard mock response JSON to be served by MockWebServer
    val MOCK_PRODUCTS_JSON = """
        [
          {
            "id": "1",
            "title": "Fjallraven - Foldsack No. 1 Backpack, Fits 15 Laptops",
            "price": 109.95,
            "description": "Your perfect pack for everyday use and walks in the forest. Stash your laptop (up to 15 inches) in the padded sleeve, your everyday",
            "category": "men's clothing",
            "image": "https://fakestoreapi.com/img/81fPKd-2AYL._AC_SL1500_.jpg",
            "rating": { "rate": 3.9, "count": 120 }
          },
          {
            "id": "2",
            "title": "Mens Casual Premium Slim Fit T-Shirts",
            "price": 22.3,
            "description": "Slim-fitting style, contrast raglan long sleeve, three-button henley placket, light weight & soft fabric for breathable and comfortable wearing.",
            "category": "men's clothing",
            "image": "https://fakestoreapi.com/img/71-3HjGNDUL._AC_SY879._SX._UX._SY._UY_.jpg",
            "rating": { "rate": 4.1, "count": 259 }
          }
        ]
    """.trimIndent()
}